#!/bin/bash
shopt -s nullglob
if [ -a GAUSSIAN ];   then
 for f in *.out; do  echo -n . > /dev/tty; a=$(grep "Sum of electronic and thermal Enthalpies=" $f);  b=$(./freq $f); echo $f $a $b; done > enthalpies.tmp
 sort -n enthalpies.tmp > enthalpies.txt
 rm enthalpies.tmp
 calculated=$(wc -l <enthalpies.txt)
 shopt -u nullglob
 total=$(ls *.gjf 2>/dev/null | wc -l)
elif [ -a ORCA ];   then
 for f in *.out; do  echo -n . > /dev/tty; a=$(grep "Total enthalpy" $f | cut -d "-" -f 2 | cut -d " " -f 1);  b=$(./freq $f); echo $f Sum of electronic and thermal Enthalpies= -$a $b; done > energies.tmp
 sort -n enthalpies.tmp > enthalpies.txt
 rm enthalpies.tmp
 calculated=$(wc -l <enthalpies.txt)
 shopt -u nullglob
 total=$(ls *.inp 2>/dev/null | wc -l)
else
 echo "ERROR: Program not supported or not properly indicated"
 exit
fi

echo
echo $calculated" Compounds calculated out of "$total
echo

