#!/bin/bash
if [ -a TSP ];   then
  tsp | grep 'running'
  tsp>que.txt
  if [ -a CREST ]; then
   awk '{name=$7; if($2=="finished" && $4=="0"){system("a=$(dirname "name") && b=$(basename "name") && echo $a $b");} if($2=="finished" && $4!="0"){system("b=$(basename "name") && cp "$3" $b.err")}}' que.txt > list.txt
   awk '{system("cp "$1"/crest_best.xyz "substr($2, 1, length($2)-4)".out"); }' list.txt
  elif [ -a XTB ]; then
   awk '{name=$7; if($2=="finished" && $4=="0"){system("a=$(dirname "name") && b=$(basename "name") && echo $a $b");} if($2=="finished" && $4!="0"){system("b=$(basename "name") && cp "$3" $b.err")}}' que.txt > list.txt
   awk '{system("cp "$1"/xtbopt.xyz "substr($2, 1, length($2)-4)".out"); }' list.txt
  elif [ -a GAUSSIAN ]; then
   awk '{name=$7; if($2=="finished" && $4=="0"){system("a=$(dirname "name") && b=$(basename "name") && echo $a $b");} if($2=="finished" && $4!="0"){system("b=$(basename "name") && cp "$3" $b.err")}}' que.txt > list.txt
   awk '{fname=substr($2, 1, length($2)-4); system("cp "$1"/"fname".log "fname".out"); }' list.txt
  else 
  awk '{name=substr($NF,6,index($NF,".")-6); if($2=="finished"){system("cp "$3" "name".out"); if($4!="0"){system("echo 'ERROR'>"name".err")}}}' que.txt 2>/dev/null
  fi  
  tsp -C
fi
if [ -a SLURM ];   then
  ./slurm_settings
  squeue -u $user
fi

