#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "use: $0 input_file"
exit
fi

if ! [ -f $1 ]; then echo "File does not exist"; exit; fi
dos2unix $1 2>/dev/null

if [ -a TSP ];   then     #User had chosen tsp task spooler
 if [ -a ORCA ];   then 
  #echo "tsp + orca"; 
  cp $1 /tmp/$1
  tsp orca /tmp/$1 >/dev/null
 fi
 if [ -a GAUSSIAN ];   then
  #echo "tsp + gaussian";
  cp $1 /tmp/$1
  tsp g09 /tmp/$1
 fi
 if [ -a CREST ];   then
  #echo "tsp + crest";
  crest_commands=$(<crestheader)
  tempdir=$(mktemp -d)
  cp $1 $tempdir
  ( cd $tempdir && tsp crest $tempdir/$1 $crest_commands )
 fi
 if [ -a XTB ];   then
  #echo "tsp + xtb";
  xtb_commands=$(<xtbheader)
  tempdir=$(mktemp -d)
  cp $1 $tempdir
  ( cd $tempdir && tsp xtb $tempdir/$1 $xtb_commands )
 fi
fi

if [ -a SLURM ];   then    #User had chosen slurm task spooler
 ./slurm_settings
 if [ -a ORCA ];   then
  #echo "slurm + orca"; #this will never work
  file=$(echo $1 | awk -F. '{print $1}')
  proc=$(grep 'proc' $1 | cut -d '=' -f 2)
  if [ -z $proc ] ; then proc="1"; fi
  mem=$(grep 'mem' $1 | cut -d '=' -f 2)
  if [ -z $mem ] ; then mem="59000MB"; fi
  pwd=$(pwd)
  cp slurm_header $file.tmp
  echo '. $g16root/g16/bsd/g16.profile       # for bash script
  export GAUSS_SCRDIR=$scratchdir/g16_$SLURM_JOBID  # def. tmp folder
  mkdir  -p $GAUSS_SCRDIR                      # the dir must exist' >> $file.tmp
  echo "
  g16 -p=$proc < $file.gjf  > $file.out
  #rmdir $GAUSS_SCRDIR
  " >> $file.tmp
  #sbatch $file.tmp #2>/dev/null
  cat $file.tmp
  rm $file.tmp
 fi
 if [ -a GAUSSIAN ];   then
  #echo "slurm + gaussian";
  file=$(echo $1 | awk -F. '{print $1}')
  proc=$(grep 'proc' $1 | cut -d '=' -f 2)
  if [ -z $proc ] ; then proc="1"; fi
  mem=$(grep 'mem' $1 | cut -d '=' -f 2)
  if [ -z $mem ] ; then mem="59000MB"; fi
  pwd=$(pwd)
  cp slurm_header $file.tmp
  echo ". $g16root/g16/bsd/g16.profile       # for bash script
  export GAUSS_SCRDIR=$scratchdir/g16_$SLURM_JOBID  # def. tmp folder
   mkdir  -p $GAUSS_SCRDIR                      # the dir must exist" >> $file.tmp
  echo "
    g16 -p=$proc < $file.gjf  > $file.out
    #rmdir $GAUSS_SCRDIR
   " >> $file.tmp
  sbatch $file.tmp #2>/dev/null
  rm $file.tmp
 fi 
fi

