#!/bin/bash
#SBATCH -N1 -n$proc   # $proc is taken directly from input file
#SBATCH --time=12:00:00
#SBATCH --mem=$mem   # $mem is taken directly from the input file
#SBATCH --error  $file.err
#SBATCH --output $file.out
#SBATCH --account= $user
#SBATCH --mail-user= # if you want to receive an email, and if it is supported by the system insert your email
#SBATCH --mail-type=END,FAIL # You will receive an email when the job is finished or failed
#SBATCH --partition= $queuename  
module load g16/C.01

