#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "use: $0 file.xyz"
exit
fi
outfile=$(basename $1 .xyz )
cat gauheader > $outfile.gjf
tail -n +3 $1 >> $outfile.gjf
echo >>$outfile.gjf
echo >>$outfile.gjf

